#!/usr/bin/env ruby

# frozen_string_literal: true

require 'bundler/setup'
require 'date'
require 'pg'

# Responsibilities:
# * Communicate with database
# * Format and display results
class ExpenseData
  def initialize
    @connection = PG.connect(dbname: 'expense')
  end

  def add_expense(amount, memo)
    date = Date.today
    sql = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3);'
    @connection.exec_params(sql, [amount, memo, date])
  end

  def delete_expense(id)
    sql = 'SELECT * FROM expenses WHERE id = $1;'
    result = @connection.exec_params(sql, [id])

    if result.ntuples == 1
      sql = 'DELETE FROM expenses WHERE id = $1;'
      @connection.exec_params(sql, [id])
      puts 'The following expense has been deleted:'
      display_expenses(result)
    else
      puts "There is no expense with the id '#{id}'."
    end
  end

  def list_expenses
    result = @connection.exec_params('SELECT * FROM expenses ORDER BY created_on ASC;')

    display_expenses(result)
  end

  def search_expenses(query)
    result = @connection.exec_params(
      'SELECT * FROM expenses WHERE memo ILIKE $1 ORDER BY created_on ASC;',
      ["%#{query}%"]
    )
    display_expenses(result)
  end

  def display_expenses(result)
    result.each do |tuple|
      columns = [tuple['id'].rjust(3),
                 tuple['created_on'].rjust(10),
                 tuple['amount'].rjust(12),
                 tuple['memo']]

      puts columns.join(' | ')
    end
  end
end

# Responsibilites:
# * Process arguments
class CLI
  def initialize
    @expense_data = ExpenseData.new
  end

  def run(arguments)
    command = arguments.shift
    case command
    when 'add'
      amount = arguments[0]
      memo = arguments[1]
      abort('You must provide an amount and memo.') unless amount && memo
      @expense_data.add_expense(amount, memo)
    when 'delete'
      @expense_data.delete_expense(arguments[0])
    when 'list'
      @expense_data.list_expenses
    when 'search'
      @expense_data.search_expenses(arguments[0])
    else
      display_help
    end
  end

  def display_help
    puts <<~HELP
      An expense recording system

      Commands:

      add AMOUNT MEMO - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP
  end
end

CLI.new.run(ARGV)
